travis:
  secure:
    BINSTAR_TOKEN: kvqRA7aL9KtdYkCeQnLp6yQhtGzThhcoXi8nNv+xrKStAykf9ivBsnCeru+MBgNw5DCgb20tzAEO3ma48AT3LCfPZh2SQvspPxEAqZCvhHIXkEotcyr3BP6drVtimcGqrWol/uK8sRv5URkuhFYOPdiQYFydhWSnj9pdrEjmBmsAPMNeFdLk7osKeGBKzxlwzpchKJg8nX5LDxJmG2NmgMW+P5QYq6mrgxzUNDyATIBOFK9Ig2bDU0wiE+tGlI4O+IA44yHaoyih3IOe6OxcKQFGFeabQnzHI0ZTxsA/+9fgRfT7QPnDHpVmYEj+O3QiS6r2Y+T5jbsSAArZy37I4WabrSkjZGVEfB9MwDhjh3sy8YIZzZqHU/jbjUURWd9SsWUMaVELXZeEiOH9jKdJD0MBYJ6wBAYWfatP3KosrB1152mm3VYwnIkerJiMx+fACeHhJ87gMSWitNZniZ8kYRTNP1N9WtVBc5xIryQi1Ir+GBY4ASrezGG/5H7iEK5VMLy1mLPhhwaOGIclds67CWKIo2bnRgVJc7c+8NKyNMttKvHy4t6FbOPBTNUv/u8Nz361Jh11E0LqzG5Ou+WGlwgB9GqVUPP/L53SeOFRf8cBFNqupHAukpzOoVICCOiOwFCLXTNhoFXI9rS/++av80GL9A/GG7nZp6wYvjUM2Q8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
