travis:
  secure:
    BINSTAR_TOKEN: PhqBW3AT6NWl2yWYJW5+QzZK+ft+65qz1KD306PRi+HGAbUpyGqXSntH0ucXLvnW8ZEzvvKHhiAttiMn6Crc7PO+esZDsSpe8uci1j5WfZSJx2ogxHbXW3feCJVf0NyS0w51TgfzcuQa2zlRWi9wEB0fSBUpFq0GOxnmtUagcWRF/kMKpgmQvpmkcdVAn5XRYCkf/7YjR1BydzLP4Ran939x7vjKUkexiy9dYyyLK3VX+phDS4lJ1kn3TrmxTRXcvKfw7N/A3HAE/q2Z/ULTpiKoMfvHFUvfBJhp7m2FgVpKkb2oV+hivXOXJFFavI79NkqjrkXpXhU6cJtg8CrfhpISnHP+46Ikl0/ZybyAo12AmWP7W/v8EC+PmNKpANliqd/DbrQYZfipMhTS4GfsHA53Lx1BXzJWzJTwj84BdcWgUO90pNBOuqla93QN1ertnbKVD8jRpkaQcZpG280YFpZ2GEqG132vgsR7yJgpLsyBmPH5orUmM7VWug8YL0c3woWbEvkKMKt0/34kw3NOWGF0Rm1OaqdlCnjj2+ooXG+SX5Mk9/qzuCQxYNvkVmmkqus9FaBWTLQDckkG6mkMzsqUVprybM2S4EsAoik2HYA4tZ6X/4QJC4FB8eWPfLYdMoMxamOf3JcghGifATs5b0ictHUb2XK3jgE2EdYOf+0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
